batch_size: 4
dataset_name: SequenceHLEPlusPlus
dataset_path: /tmp/564410.tinygpu/HLEDataset/dataset/
eval_threshold: 0.4
features:
- 32
- 64
- 128
- 256
- 512
gauss_window: 5
heatmapaxis: 3
image_height: 512
image_width: 256
in_channels: 6
is_color: false
kernel3d_size: 3
keypoint_lambda: 0.001
keypoint_regularization_at: 1000
last_epoch: 99
learning_rate: 0.1
loss_weights:
- 1.0
- 1.0
- 1.0
- 1.0
maxima_window: 11
model: TwoDtoThreeDNet
nn_threshold: 3.0
num_classes: 4
num_epochs: 100
num_workers: 4
optimizer: sgd
out_channels: 4
pad_keypoints: 200
sequence_length: 6
shuffle_training: true
temporal_lambda: 0.01
temporal_regularization_at: 1000
threshold: 0.3
train_keys: CF,CM,LS,RH,SS,TM,MK,MS
val_keys: DD,FH
