model: 'UNet'

learning_rate: 0.01
batch_size: 4
features: [32, 64, 128, 256, 512, 1024]
eval_threshold: 0.4
num_workers: 1
shuffle_training: false

last_epoch: 0
num_epochs: 100
num_classes: 4

image_height: 512
image_width: 256

temporal_regularization_at: 10
temporal_lambda: 0.01

keypoint_regularization_at: 10
nn_threshold: 3.0
keypoint_lambda: 0.05

dataset_name: SBHLEPlusPlus
dataset_path: '../HLEDataset/dataset/'
train_keys: CF,CM,DD,FH,LS,RH,SS,TM
val_keys: MK,MS

gauss_window: 5
maxima_window: 11
threshold: 0.3
heatmapaxis: 3
pad_keypoints: 200

is_color: false